#!/usr/bin/env python3
"""Build the public site and recorded sandbox demo without third-party packages.

Run on Linux, macOS or WSL: python3 scripts/build_site.py --out _site
Headline evidence is read from Git HEAD, never from an uncommitted experiment.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from html import escape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
MARKER = ".belay-site-build"
MARKER_CONTENT = "Generated by scripts/build_site.py\n"
RESERVED = {"evidence.json", "recovery-desk.html", MARKER}
VERDICTS = {
    "clean", "escalated", "refused", "duplicate_effect",
    "unauthorized_effect", "misattributed", "phantom_success", "lost_work",
}
SAFE_VERDICTS = {"clean", "escalated", "refused", "lost_work"}


def evidence_from_records(
    findings: dict, matrix: dict, adjudication: dict, commit: str, repository: str,
) -> dict:
    """Cross-check the small public summary against its committed raw records."""
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError("evidence provenance requires a full Git commit SHA")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("repository must be an owner/name GitHub repository")
    trials = matrix["trials"]
    if not trials or not all(t["crashed_as_asked"] is True for t in trials):
        raise ValueError("the recorded matrix must confirm every requested crash")
    if findings["n_crashes_confirmed"] != len(trials):
        raise ValueError("findings crash count disagrees with the matrix")
    config = matrix["config"]
    expected = (len(config["runtimes"]) * len(config["tiers"])
                * len(config["crash_points"]) * 2 * config["reps"])
    if len(trials) != expected:
        raise ValueError("the recorded crash matrix is incomplete")

    anchored = [t for t in trials if t["runtime"] == "anchored"]
    verdicts = Counter(t["verdict"] for t in anchored)
    if not anchored or set(verdicts) - VERDICTS:
        raise ValueError("missing anchored trials or an unrecognized verdict")
    violations = sum(v for k, v in verdicts.items() if k not in SAFE_VERDICTS)
    summary = findings["runtimes"]["anchored"]
    if (summary["trials"] != len(anchored)
            or summary["violations"] != violations
            or summary["verdicts"] != dict(verdicts)):
        raise ValueError("anchored findings disagree with the raw trials")

    cases = adjudication["cases"]
    validated = [c for c in cases if c["pipeline"] == "validated"]
    grades = Counter(c["grade"] for c in validated)
    if not validated or set(grades) - {"resolved", "false", "abstained"}:
        raise ValueError("missing validated cases or an unrecognized grade")
    adj_summary = adjudication["summary"]
    recorded_grades = adj_summary["by_pipeline"]["validated"]
    if (adj_summary["cases"] != len(cases)
            or any(recorded_grades.get(k, 0) != grades[k]
                   for k in set(recorded_grades) | set(grades))
            or adj_summary["validated"]["cases"] != len(validated)
            or adj_summary["validated"]["resolved"] != grades["resolved"]):
        raise ValueError("adjudication summary disagrees with the raw cases")

    repository_url = f"https://github.com/{repository}"
    source = f"{repository_url}/blob/{commit}/"
    sources = {
        "matrix": source + "results/matrix.json",
        "findings": source + "results/findings.json",
        "adjudication": source + "results/adjudication.json",
        "contract": source + "CONTRACT.md",
        "writeup": source + "FINDINGS.md",
    }
    return {
        "schema_version": 1,
        "source_commit": commit,
        "repository_url": repository_url,
        "scope": (
            "Committed synthetic experiments using sandbox services and real "
            "process kills. These observations are not production failure rates "
            "or a guarantee outside CONTRACT.md."
        ),
        "metrics": {
            "crash_trials": {
                "confirmed": len(trials), "source_url": sources["matrix"],
            },
            "anchored": {
                "violations": violations, "trials": len(anchored),
                "source_url": sources["findings"],
            },
            "adjudication": {
                "false_resolutions": grades["false"],
                "resolved": grades["resolved"],
                "abstained": grades["abstained"],
                "trials": len(validated),
                "source_url": sources["adjudication"],
            },
        },
        "sources": sources,
        "recovery_desk": {
            "path": "recovery-desk.html",
            "execution": "recorded sandbox runs generated during this build",
            "agent": "simulated heuristic, no live model call",
        },
    }


def committed_evidence(root: Path, repository: str) -> dict:
    commit = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True,
    ).strip()
    records = []
    for name in ("findings", "matrix", "adjudication"):
        raw = subprocess.check_output(
            ["git", "-C", str(root), "show", f"{commit}:results/{name}.json"],
        )
        records.append(json.loads(raw))
    return evidence_from_records(*records, commit, repository)


def output_path(root: Path, requested: Path) -> Path:
    """Only replace a dedicated, marked build folder within this checkout."""
    root = root.resolve()
    candidate = requested if requested.is_absolute() else root / requested
    lexical = Path(os.path.abspath(candidate))
    resolved = candidate.resolve()
    if lexical != resolved:
        raise ValueError("output cannot pass through a symbolic link or junction")
    try:
        relative = resolved.relative_to(root)
    except ValueError as exc:
        raise ValueError("output must stay within the repository") from exc
    if not (relative.parts == ("_site",)
            or (len(relative.parts) >= 2 and relative.parts[0] == "tmp-runs")):
        raise ValueError("output must be _site or a folder below tmp-runs/")
    if resolved.exists():
        marker = resolved / MARKER
        if not resolved.is_dir() or (
            any(resolved.iterdir()) and (
                not marker.is_file() or marker.is_symlink()
                or marker.read_text(encoding="utf-8") != MARKER_CONTENT
            )
        ):
            raise ValueError("refusing to replace an existing non-build directory")
    return resolved


def copy_site(source: Path, destination: Path) -> None:
    if source.is_symlink() or not (source / "index.html").is_file():
        raise ValueError("site/index.html is required in a regular source directory")
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        if path.is_symlink() or path.resolve() != path.absolute():
            raise ValueError(f"site assets cannot be symbolic links: {relative}")
        if any(part.startswith(".") for part in relative.parts):
            raise ValueError(f"hidden site assets are not published: {relative}")
        if relative.parts[0] in RESERVED:
            raise ValueError(f"site asset uses a generated filename: {relative}")
        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
        else:
            raise ValueError(f"site asset must be a regular file: {relative}")


def bind_evidence(html: str, evidence: dict) -> str:
    """Make the published HTML authoritative even when JavaScript is disabled."""
    metrics = evidence["metrics"]
    values = {
        "metric-crashes": metrics["crash_trials"]["confirmed"],
        "metric-violations": metrics["anchored"]["violations"],
        "metric-trials": metrics["anchored"]["trials"],
        "metric-resolved": metrics["adjudication"]["resolved"],
        "metric-adjudications": metrics["adjudication"]["trials"],
        "metric-false": metrics["adjudication"]["false_resolutions"],
        "metric-abstained": metrics["adjudication"]["abstained"],
    }
    offsets = [0]
    for line in html.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    replacements = []
    counts = Counter()

    class Binding(HTMLParser):
        pending = None

        def position(self):
            line, column = self.getpos()
            return offsets[line - 1] + column

        def handle_starttag(self, tag, attrs):
            if self.pending:
                raise ValueError("metric fields must contain only numeric text")
            ids = [value for key, value in attrs if key == "id"]
            if len(ids) > 1:
                raise ValueError("HTML elements cannot have duplicate id attributes")
            field = ids[0] if ids else None
            raw_tag = self.get_starttag_text()
            if field in values:
                counts[field] += 1
                self.pending = (tag, field, self.position() + len(raw_tag))
            sources = [value for key, value in attrs if key == "data-source"]
            if sources:
                if len(sources) != 1 or sources[0] not in evidence["sources"]:
                    raise ValueError("unrecognized or duplicate evidence source")
                url = escape(evidence["sources"][sources[0]], quote=True)
                replaced, total = re.subn(
                    r"\bhref\s*=\s*([\"']).*?\1", lambda _: f'href="{url}"',
                    raw_tag, flags=re.IGNORECASE,
                )
                if total != 1:
                    raise ValueError("each evidence source needs exactly one href")
                replacements.append((self.position(), self.position() + len(raw_tag), replaced))

        def handle_endtag(self, tag):
            if self.pending:
                expected_tag, field, start = self.pending
                end = self.position()
                if tag != expected_tag or not re.fullmatch(r"\s*\d+\s*", html[start:end]):
                    raise ValueError("metric fields must contain only numeric text")
                replacements.append((start, end, str(values[field])))
                self.pending = None

    parser = Binding(convert_charrefs=False)
    parser.feed(html)
    parser.close()
    if parser.pending or any(counts[field] != 1 for field in values):
        raise ValueError("site must contain exactly one of every audited metric ID")
    for start, end, replacement in sorted(replacements, reverse=True):
        html = html[:start] + replacement + html[end:]
    return html


def check_local_links(output: Path) -> None:
    """Catch missing assets and root-relative URLs before publishing a project site."""
    class Links(HTMLParser):
        def __init__(self):
            super().__init__()
            self.urls = []

        def handle_starttag(self, tag, attrs):
            for name, value in attrs:
                if name in {"href", "src"} and value:
                    self.urls.append(value)

    for page in output.rglob("*.html"):
        links = Links()
        links.feed(page.read_text(encoding="utf-8"))
        for value in links.urls:
            url = urlsplit(value)
            if url.scheme or url.netloc or not url.path:
                continue
            path = unquote(url.path)
            if path.startswith("/"):
                raise ValueError(f"use a project-relative site URL: {value}")
            target = (page.parent / path).resolve()
            if not target.is_relative_to(output):
                raise ValueError(f"site link escapes the build output: {value}")
            if not target.is_file() and not (target / "index.html").is_file():
                raise ValueError(f"missing local site target in {page.name}: {value}")


def build_site(root: Path, requested: Path, repository: str) -> Path:
    root = root.resolve()
    output = output_path(root, requested)
    evidence = committed_evidence(root, repository)
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".pages-build-", dir=output.parent))
    try:
        copy_site(root / "site", staging)
        index = staging / "index.html"
        index.write_text(
            bind_evidence(index.read_text(encoding="utf-8"), evidence),
            encoding="utf-8",
        )
        subprocess.run(
            [sys.executable, str(root / "viewer" / "build_viewer.py"),
             "--out", str(staging / "recovery-desk.html")],
            cwd=root, check=True, timeout=180,
        )
        viewer = staging / "recovery-desk.html"
        if not viewer.is_file() or viewer.stat().st_size == 0:
            raise ValueError("Recovery Desk generation did not produce an HTML file")
        (staging / "evidence.json").write_text(
            json.dumps(evidence, indent=2) + "\n", encoding="utf-8",
        )
        (staging / ".nojekyll").touch()
        (staging / MARKER).write_text(MARKER_CONTENT, encoding="utf-8")
        check_local_links(staging)
        # Validate again immediately before removing only this managed build.
        output_path(root, output)
        if output.exists():
            shutil.rmtree(output)
        staging.rename(output)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("_site"))
    parser.add_argument(
        "--repository", default=os.environ.get("GITHUB_REPOSITORY", "Frank-7/Belay"),
        help="owner/name used in commit-pinned evidence links",
    )
    args = parser.parse_args(argv)
    if os.name != "posix":
        parser.error("the recorded SIGKILL demo requires Linux, macOS or WSL")
    try:
        output = build_site(ROOT, args.out, args.repository)
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as exc:
        parser.exit(1, f"site build failed: {exc}\n")
    print(f"Built {output}; preview with python3 -m http.server --directory {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
